/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Jul 2 2018
 * Processor: AT89C52
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

void main(void)
 { 
   // Write your code here
   while (1)
      ;
 }