# MPLAB IDE generated this makefile for use with GNU make.
# Project: seven_segment_display_pic.mcp
# Date: Mon Jul 02 11:43:20 2018

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

seven_segment_display_pic.cof : seven_segment_display_pic.o
	$(LD) /p18F4520 /l"C:\Program Files (x86)\Microchip\mplabc18\v3.47\lib" "seven_segment_display_pic.o" /u_CRUNTIME /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"seven_segment_display_pic.cof" /M"seven_segment_display_pic.map" /W

seven_segment_display_pic.o : seven_segment_display_pic.c C:/Program\ Files\ (x86)/Microchip/mplabc18/v3.47/h/p18f4520.h
	$(CC) -p=18F4520 "seven_segment_display_pic.c" -fo="seven_segment_display_pic.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

clean : 
	$(RM) "seven_segment_display_pic.o" "seven_segment_display_pic.cof" "seven_segment_display_pic.hex"

