/* Main.c file generated by New Project wizard
 *
 * Created:   Sat May 28 2011
 * Processor: LPC2101
 * Compiler:  GCC for ARM
 */

#include <LPC2103.h>

int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
