/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Jul 2 2018
 * Processor: PIC18F4520
 * Compiler:  MPLAB C18
 */

#include <p18f4520.h>

void main()
 { 
   // Write your code here
   while (1)
      ;
 }
